# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='deleted_at',
        ),
    ]
