# Generated by Django 4.0.6 on 2022-08-04 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_productimage_delete_imaging'),
        ('user', '0003_remove_inventory_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.image', verbose_name='프로필 이미지'),
        ),
    ]
