# Generated by Django 4.1 on 2022-08-16 20:03

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user.user_directory_path, verbose_name='프로필 이미지'),
        ),
    ]
