# Generated by Django 4.0.6 on 2022-07-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_merge_20220731_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('status', models.IntegerField(choices=[(0, 'IN_PROGRESS'), (1, 'COMPLETED')], db_index=True, default=0, null=True, verbose_name='상태')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='거래 완료 일시')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='물품')),
                ('product_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgroup', verbose_name='물품 그룹')),
            ],
            options={
                'verbose_name': 'Dealing',
                'verbose_name_plural': 'Dealings',
                'db_table': 'dealings',
            },
        ),
    ]
