# Generated by Django 4.0.6 on 2022-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealing',
            name='deleted_at',
        ),
    ]
