# Generated by Django 4.0.6 on 2022-08-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productgroup_auction'),
        ('dealing', '0003_remove_dealing_status_dealing_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealing',
            name='product',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealing', to='product.product', verbose_name='물품'),
        ),
        migrations.AlterField(
            model_name='dealing',
            name='product_group',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealing', to='product.productgroup', verbose_name='물품 그룹'),
        ),
    ]
