# Generated by Django 4.1 on 2022-08-15 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealing', '0005_dealingevaluation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealingevaluation',
            name='dealing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealing_evaluations', to='dealing.dealing', verbose_name='거래 내역'),
        ),
    ]
