# Generated by Django 4.0.6 on 2022-08-04 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='경매 제목')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='경매 설명')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='경매 시작 일시')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='경매 종료 일시')),
                ('dealing_type', models.IntegerField(choices=[(0, 'direct'), (1, 'delivery')], db_index=True, default=0, verbose_name='거래 방법')),
                ('product_groups_count', models.IntegerField(default=0, null=True, verbose_name='참여자 수')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'auctions',
            },
        ),
        migrations.CreateModel(
            name='InterestedAuction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction', verbose_name='경매장')),
            ],
            options={
                'verbose_name': 'InterestedAuction',
                'verbose_name_plural': 'InterestedAuctions',
                'db_table': 'interested_auctions',
            },
        ),
    ]
