# Generated by Django 4.0.6 on 2022-07-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='dealing_type',
            field=models.IntegerField(choices=[(1, 'delivery'), (0, 'direct')], db_index=True, default=0, verbose_name='거래 방법'),
        ),
    ]
