# Generated by Django 4.0.6 on 2022-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_dealing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dealing_type',
            field=models.IntegerField(choices=[(0, 'direct'), (1, 'delivery')], db_index=True, default=0, verbose_name='거래 방법'),
        ),
    ]
