# Generated by Django 4.0.6 on 2022-08-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_auction_end_at'),
        ('auction', '0004_auction_product_groups_count'),
    ]

    operations = [
    ]
