# Generated by Django 4.0.6 on 2022-08-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_product_groups_count'),
        ('auction', '0004_interestedauction'),
    ]

    operations = [
    ]
