# Generated by Django 4.0.6 on 2022-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_merge_20220802_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='deleted_at',
        ),
    ]
