# Generated by Django 4.0.6 on 2022-08-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_interestedauction'),
        ('auction', '0007_auction_title'),
    ]

    operations = [
    ]
