# Generated by Django 4.0.6 on 2022-08-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_merge_20220802_2107'),
        ('auction', '0008_merge_0004_interestedauction_0007_auction_title'),
    ]

    operations = [
    ]
