# Generated by Django 4.0.6 on 2022-08-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_merge_20220803_1944'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interestedauction',
            constraint=models.UniqueConstraint(fields=('user', 'auction'), name='unique_interested_auction_by_user'),
        ),
    ]
