# Generated by Django 4.0.6 on 2022-08-08 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_interestedauction_unique_interested_auction_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestedauction',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_auctions', to='auction.auction', verbose_name='경매장'),
        ),
    ]
