# Generated by Django 4.1 on 2022-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auction_interested_auctions_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='dealing_type',
            field=models.IntegerField(choices=[(0, 'direct'), (1, 'delivery'), (2, 'all')], db_index=True, default=0, verbose_name='거래 방법'),
        ),
    ]
