# Generated by Django 4.1 on 2022-08-16 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_alter_user_avatar'),
        ('product', '0019_alter_productgroup_user'),
        ('auction', '0013_alter_auction_dealing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(through='product.ProductGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='product.product', verbose_name='물품'),
        ),
    ]
