# Generated by Django 4.0.6 on 2022-08-04 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('name', models.CharField(max_length=100, verbose_name='물품 명')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='물품 설명')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('quality', models.IntegerField(choices=[(1, 'very_poor'), (2, 'poor'), (3, 'good'), (4, 'very_good'), (5, 'excellent')], db_index=True, default=3, verbose_name='품질')),
                ('status', models.IntegerField(choices=[(0, 'hidden'), (1, 'in_auction'), (2, 'dealing'), (3, 'dealed')], db_index=True, default=0, verbose_name='상태')),
                ('abstract', models.CharField(blank=True, max_length=100, null=True, verbose_name='요약')),
                ('dealing_at', models.DateTimeField(blank=True, null=True, verbose_name='거래 시작 일시')),
                ('dealed_at', models.DateTimeField(blank=True, null=True, verbose_name='거래 완료 일시')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 명')),
                ('primary', models.BooleanField(default=False, verbose_name='주요 분류 유무')),
                ('display_order', models.IntegerField(default=0, verbose_name='전시 순서')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategories',
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('money', models.IntegerField(default=0, null=True, verbose_name='추가 금액')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='물품 그룹 설명')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.auction', verbose_name='경매')),
            ],
            options={
                'verbose_name': 'ProductGroup',
                'verbose_name_plural': 'ProductGroups',
                'db_table': 'product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='물품')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productgroup', verbose_name='물품 그룹')),
            ],
            options={
                'verbose_name': 'ProductGroupItem',
                'verbose_name_plural': 'ProductGroupItems',
                'db_table': 'product_group_items',
            },
        ),
        migrations.AddField(
            model_name='productgroup',
            name='products',
            field=models.ManyToManyField(through='product.ProductGroupItem', to='product.product'),
        ),
    ]
