# Generated by Django 4.0.6 on 2022-07-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deleted_at',
        ),
    ]
