# Generated by Django 4.0.6 on 2022-07-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_quality_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.IntegerField(choices=[(1, '하'), (2, '중하'), (3, '중'), (4, '중상'), (5, '상')], default=3, verbose_name='품질'),
        ),
    ]
