# Generated by Django 4.0.6 on 2022-07-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcategory_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='전시 순서'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='주요 분류 유무'),
        ),
    ]
