# Generated by Django 4.0.6 on 2022-07-31 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_manager', '0001_initial'),
        ('product', '0006_product_thumbnail_product_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거래 완료 일시'),
        ),
        migrations.AddField(
            model_name='product',
            name='dealing_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='거래 시작 일시'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'hidden'), (1, 'in_auction'), (2, 'dealing'), (3, 'dealed')], db_index=True, default=0, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(choices=[(1, '하'), (2, '중하'), (3, '중'), (4, '중상'), (5, '상')], db_index=True, default=3, verbose_name='품질'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='file_manager.image', verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='유저'),
        ),
    ]
