# Generated by Django 4.0.6 on 2022-07-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_dealed_at_product_dealing_at_product_status_and_more'),
        ('product', '0007_productgroup_productgroupitem'),
    ]

    operations = [
    ]
