# Generated by Django 4.0.6 on 2022-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(choices=[(1, 'very_poor'), (2, 'poor'), (3, 'good'), (4, 'very_good'), (5, 'excellent')], db_index=True, default=3, verbose_name='품질'),
        ),
    ]
