# Generated by Django 4.0.6 on 2022-08-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productgroup_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productgroupitem',
            name='deleted_at',
        ),
    ]
