# Generated by Django 4.0.6 on 2022-08-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_productcategory_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productgroup',
            constraint=models.UniqueConstraint(fields=('user', 'auction'), name='unique_product_group_in_auction_by_user'),
        ),
    ]
