# Generated by Django 4.0.6 on 2022-08-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_images'),
        ('product', '0013_productgroup_unique_product_group_in_auction_by_user'),
    ]

    operations = [
    ]
