# Generated by Django 4.0.6 on 2022-08-04 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_merge_20220803_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(db_index=True, default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='품질'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수량'),
        ),
    ]
