# Generated by Django 4.0.6 on 2022-08-04 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_quality_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.IntegerField(db_index=True, default=3, validators=[django.core.validators.MaxValueValidator(5, message='품질은 5까지 설정할 수 있습니다.'), django.core.validators.MinValueValidator(1, message='품질은 0보다 커야 합니다.')], verbose_name='품질'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='수량은 0보다 커야 합니다.')], verbose_name='수량'),
        ),
    ]
