# Generated by Django 4.0.6 on 2022-08-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealing', '0003_remove_dealing_status_dealing_auction'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dealing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='dealing.dealing', verbose_name='거래'),
        ),
    ]
